import type { Instructor, Review, Course, Module } from '@/types';

export const instructors: Instructor[] = [
  {
    id: 'inst-1',
    name: 'Bunga Citra',
    title: 'Lead UX Designer',
    bio: 'Bunga adalah seorang desainer dengan pengalaman lebih dari 10 tahun dalam menciptakan pengalaman pengguna yang intuitif dan indah untuk aplikasi web dan seluler.',
    avatarUrl: 'https://placehold.co/100x100.png',
  },
  {
    id: 'inst-2',
    name: 'Budi Santoso',
    title: 'Senior Software Engineer',
    bio: 'Budi adalah seorang full-stack developer yang berspesialisasi dalam React dan Node.js. Dia suka membangun aplikasi yang skalabel dan beperforma tinggi, serta berbagi ilmunya dengan orang lain.',
    avatarUrl: 'https://placehold.co/100x100.png',
  },
];

export const reviews: Review[] = [
  {
    id: 'rev-1',
    user: { name: 'Alya', avatarUrl: 'https://placehold.co/40x40.png' },
    rating: 5,
    comment: 'Kursus ini luar biasa! Saya belajar banyak dan instrukturnya fantastis.',
    createdAt: '2 minggu lalu',
  },
  {
    id: 'rev-2',
    user: { name: 'Bayu', avatarUrl: 'https://placehold.co/40x40.png' },
    rating: 4,
    comment: 'Materi yang bagus dan terstruktur dengan baik. Beberapa bagian sedikit terlalu cepat.',
    createdAt: '1 bulan lalu',
  },
];

const modules: Module[] = [
  {
    id: 'mod-1',
    title: 'Module 1: Introduction to Web Development',
    lessons: [
      { id: 'l-1', title: 'Understanding HTML & CSS', duration: '45min' },
      { id: 'l-2', title: 'JavaScript Fundamentals', duration: '1hr 15min' },
    ],
  },
  {
    id: 'mod-2',
    title: 'Module 2: Advanced React Concepts',
    lessons: [
        { id: 'l-3', title: 'State Management with Redux', duration: '2hr' },
        { id: 'l-4', title: 'React Hooks in-depth', duration: '1hr 30min' },
    ],
  },
];

export const courses: Course[] = [
  {
    id: '1',
    title: 'The Complete Web Development Bootcamp',
    category: 'Development',
    description: 'Learn to build modern web applications with the MERN stack.',
    longDescription: 'This comprehensive bootcamp covers everything you need to know to become a full-stack web developer. You will learn HTML, CSS, JavaScript, React, Node.js, Express, and MongoDB. The course includes hands-on projects and real-world examples to solidify your understanding.',
    price: 7485000,
    imageUrl: 'https://placehold.co/600x400.png',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    rating: 4.8,
    reviewCount: 1250,
    instructor: instructors[1],
    reviews: reviews,
    modules: modules,
    features: ['20+ hours of video', 'Downloadable resources', 'Certificate of completion', 'Lifetime access'],
    courseDate: new Date('2024-09-15T00:00:00Z'),
    courseTime: '09:00',
    level: 'Beginner',
    schedule: 'Flexible',
    status: 'Published',
  },
  {
    id: '2',
    title: 'UI/UX Design Masterclass',
    category: 'Design',
    description: 'Master the art of user interface and user experience design.',
    longDescription: 'In this masterclass, you will learn the principles of UI/UX design, from user research and wireframing to prototyping and usability testing. You will work on real-world projects to build a strong portfolio.',
    price: 5985000,
    imageUrl: 'https://placehold.co/600x400.png',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    rating: 4.9,
    reviewCount: 980,
    instructor: instructors[0],
    reviews: reviews,
    modules: modules,
    features: ['30+ hours of video', 'Figma design files', 'Certificate of completion', 'Lifetime access'],
    courseDate: new Date('2024-10-01T00:00:00Z'),
    courseTime: '13:00',
    level: 'Beginner',
    schedule: 'Flexible',
    status: 'Draft',
  },
  {
    id: '3',
    title: 'Digital Marketing Fundamentals',
    category: 'Marketing',
    description: 'A beginner-friendly guide to digital marketing channels.',
    longDescription: 'This course provides a complete overview of digital marketing, including SEO, social media marketing, email marketing, and content marketing. Learn how to create and execute effective marketing campaigns.',
    price: 3735000,
    imageUrl: 'https://placehold.co/600x400.png',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    rating: 4.7,
    reviewCount: 750,
    instructor: instructors[0],
    reviews: reviews,
    modules: modules,
    features: ['15+ hours of video', 'Marketing templates', 'Certificate of completion', 'Lifetime access'],
    level: 'Beginner',
    schedule: 'Fixed',
    status: 'Published',
  },
  {
    id: '4',
    title: 'Startup Business Management',
    category: 'Business',
    description: 'Learn the essentials of starting and managing a successful business.',
    longDescription: 'This course covers the key aspects of entrepreneurship, from idea validation and business planning to fundraising and scaling. Gain the skills and knowledge to turn your startup idea into a reality.',
    price: 8985000,
    imageUrl: 'https://placehold.co/600x400.png',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    rating: 4.8,
    reviewCount: 1100,
    instructor: instructors[1],
    reviews: reviews,
    modules: modules,
    features: ['25+ hours of video', 'Business plan templates', 'Certificate of completion', 'Lifetime access'],
    level: 'Intermediate',
    schedule: 'Flexible',
    status: 'Draft',
  },
  {
    id: '5',
    title: 'Advanced CSS and Sass',
    category: 'Development',
    description: 'Take your CSS skills to the next level with advanced techniques.',
    longDescription: 'Dive deep into modern CSS features like Flexbox, Grid, and Animations. Learn how to write clean, efficient, and reusable code with Sass. This course is perfect for front-end developers looking to level up their styling skills.',
    price: 2985000,
    imageUrl: 'https://placehold.co/600x400.png',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    rating: 4.9,
    reviewCount: 850,
    instructor: instructors[0],
    reviews: reviews,
    modules: modules,
    features: ['10+ hours of video', 'Project source code', 'Certificate of completion', 'Lifetime access'],
    level: 'Advanced',
    schedule: 'Flexible',
    status: 'Published',
  },
  {
    id: '6',
    title: 'Data Science with Python',
    category: 'Development',
    description: 'Unlock the power of data with Python, Pandas, and Matplotlib.',
    longDescription: 'This course is your complete guide to data science using Python. You will learn data analysis, visualization, and machine learning techniques with popular libraries like NumPy, Pandas, and Scikit-learn.',
    price: 7485000,
    imageUrl: 'https://placehold.co/600x400.png',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    rating: 4.8,
    reviewCount: 2300,
    instructor: instructors[1],
    reviews: reviews,
    modules: modules,
    features: ['40+ hours of video', 'Jupyter notebooks', 'Certificate of completion', 'Lifetime access'],
    level: 'Intermediate',
    schedule: 'Fixed',
    status: 'Draft',
  },
];
